services:
  backend:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "5555:8080"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://user:password@db/mydatabase
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_yarn:/app/.yarn
    ports:
      - "5151:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - python_app_data:/var/lib/mysql

volumes:
  python_app_data:
  frontend_node_modules:
  frontend_yarn:
